// generated by mBlock5 for mBot
// codes make you happy

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

MeDCMotor motor_9(9);
MeDCMotor motor_10(10);
//These functions are not to be modified for accuracy of robot, only modify the Main function, as that is the function that the robot will perform when the button
//is pressed
void move(int direction, int speed) {
  int leftSpeed = 0;
  int rightSpeed = 0;
  if(direction == 1) {
    leftSpeed = speed;
    rightSpeed = speed;
  } else if(direction == 2) {
    leftSpeed = -speed;
    rightSpeed = -speed;
  } else if(direction == 3) {
    leftSpeed = -speed;
    rightSpeed = speed;
  } else if(direction == 4) {
    leftSpeed = speed;
    rightSpeed = -speed;
  }
  motor_9.run((9) == M1 ? -(leftSpeed) : (leftSpeed));
  motor_10.run((10) == M1 ? -(rightSpeed) : (rightSpeed));
}
void TurnRight(){

  move(4, 50 / 100.0 * 255);
  _delay(0.65);
  move(4, 0);
  _delay(1);

}
void TurnLeft(){

  move(3, 50 / 100.0 * 255);
  _delay(0.65);
  move(3, 0);
  _delay(1);

}
void Main(){
  TurnLeft();
  MoveForward(1000);
  TurnRight();
  MoveBackward(1000);
  
  
  

}

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}
void MoveBackward(int time){
  motor_9.run(155);
  motor_10.run(-155);
  delay(time);
  motor_9.stop();
  motor_10.stop();
  delay(25);
}
void MoveForward(int time){
  motor_9.run(-155);
  motor_10.run(155);
  delay(time);
  motor_9.stop();
  motor_10.stop();
  delay(25);
}
void setup() {
  pinMode(A7, INPUT);
  while(1) {
      if((0 ^ (analogRead(A7) > 10 ? 0 : 1))){
        _delay(1);
        Main();

      }

      _loop();
  }

}

void _loop() {
}

void loop() {
  _loop();
}

